---
title: "Hypothesis Generation, Research Methods, and Research Design"
author: "Brian Kissell"
date: "2020-07-07T02:00:00Z"
output: html_document
featured: True
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

An interesting thing about the field of psychology is that few people outside of the discipline have any idea of what it is, and yet almost everyone has a strong intuition related to the field. One example that I see frequently is the assumption that psychology is closely related to psychotherapy (although real psychotherapy usually does not match what people are imagining either). In reality, for a large proportion of psychologists, psychology has almost nothing to do with psychotherapy. Instead, psychology basically refers to a field in which scientists and researchers study people as individuals (e.g., they might be interested in behavior or cognition.) For example, I was trained as an applied experimental social psychologist, and as such I focused most of my research on utilizing the best methodological and statistically robust techniques towards understanding the topic of attitude and belief formation (i.e., why do people believe the things that they do?). 

I bring this up because as a data scientist I see signs of a similar issue related to research design and hypothesis generation. Most people have a strong intuition that these topics are something that they are not, and thus may inaccurately estimate their ability to design studies, and or generate hypotheses. I find this to be interesting as a researcher who was not originally trained within a computer-science-oriented field. It seems completely obvious that for one to become a great programmer, that individual will need to engage in a tremendous amount of practice, and this process can take a significant amount of time. I would argue that the same could be said for study design, and hypothesis generation. It could also be said of the skill to detect important questions, and an ability to frame those questions in a theoretically sensible manner.

I believe that one of the largest benefits from an education within the field of psychology is that research design, hypothesis generation, theory generation, and critical thinking skills are prioritized. For example, for the past six years, I have participated in multiple journal article reading groups, which took place almost every week. Thus, I was able to spend multiple hours every week considering and debating the strengths, and weaknesses of differing studies, usually focusing on how the questions being asked, the theory being developed, and the methods and statistics being utilized could be improved. In addition, a large portion of all of my coursework was focused on similar issues. I was also able to gain hands-on experience as I led teams on more than twenty research projects, which included hypothesis generation, study design, data collection (and web scraping), statistical analysis, and reporting. I thus have significant training with hypothesis generation, experimental design, survey design, a/b testing, power analysis, and sampling methods. I also have experience designing and constructing new scales and measures, along with experience in validating those measures.