---
title: "Prior Research Studies"
author: "Brian Kissell"
date: "6/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Unpublished Manuscripts

Vohs, K. D., Schmeichel, B. J., Lohmann, S., Gronau, Q.… Kissell, B. L…. Wagenmakers, E.-J., & Albarracín, D. (2019). A preregistered paradigmatic test of the ego depletion effect. Unpublished manuscript, University of Minnesota, Minneapolis MN. 

Kissell, B., Gibson, B., Prewett, M., Motyl, M. (2019).  A meta-analytic evaluation of biased assimilation and polarization. Unpublished manuscript.

Kissell, B., Gibson, B., Bushman, B. (2019). The influence of overvaluation on narcissism. Unpublished manuscript.

Kissell, B., Gibson, B. (2018). The impact of physical position and prayer on cognitive style. Unpublished manuscript.

Kissell, B. (2017). Has Psychology Always Been So Ideologically Biased? A Historical Approach. Unpublished manuscript.

Kissell, B. L., Davoli, C. C., Scherr, A. S., Gibson, B. (2019). Profundity, truth, and bullshit: An investigation of the bullshit receptivity scale (BRS). Unpublished manuscript.

## Data Sets

Kissell, B. L., Gibson, B. (2020). Construction of the Perceived Threat to Identity Scale (PTI) . Unpublished raw data. (link to file)

Kissell, B. L., Gibson, B. (2020). Experimental Evaluation of the Perceived Threat to Identity Scale (PTI) and its Relationship to Conspiracy Ideation, Political Ideology, and Authoritarianism. Unpublished raw data. (link to file)

Kissell, B. L., Gibson, B. (2020). Trait Moderators of Biased Assimilation and Attitude Polarization. Unpublished raw data. (link to file)

Kissell, B. L. (2019). Textual analysis of speeches from leaders of the Church of Jesus Christ of Latter-day Saints. Unpublished raw data. (link to file)

Kissell, B. L., Gibson, B., Prewett, M., Motyl, M. (2019).  A meta-analytic evaluation of biased assimilation and polarization.  Unpublished raw data. (link to file)

Kissell, B. L., Gibson, B., Bushman, B. (2019). The influence of overvaluation on narcissism: Study 1. Unpublished raw data. (link to file)

Kissell, B. L., Gibson, B., Bushman, B. (2019). The influence of overvaluation on narcissism:Study 2. Unpublished raw data. (link to file)

Vohs, K. D., Schmeichel, B. J., Lohmann, S., Gronau, Q.… Kissell, B. L…. Wagenmakers, E.-J., & Albarracín, D. (2019). A preregistered paradigmatic test of the ego depletion effect: Kissell dataset. Unpublished raw data. (link to file) 

Kissell, B. L., Gibson, B. (2019). The effect of experimenter presence on ego-depletion. Unpublished raw data. (link to file) 

Kissell, B. L., Gibson, B. (2018). The impact of physical position and prayer on cognitive style. Unpublished raw data. (link to file) 

Kissell, B. L., Davoli, C. C., Scherr, A. S., Gibson, B. (2019). Profundity, Truth, and Bullshit: An Investigation of the Bullshit Receptivity Scale (BRS). Unpublished raw data. (link to file) 

Kissell, B. L., Gibson, B. (2019). Religious decline and contemplation on authoritarianism, religious beliefs, evaluative bias, and political beliefs. Unpublished raw data. (link to file). 

Kissell, B. L., Gibson, B. (2019). Religious decline and source of information on authoritarianism, religious belief, evaluative bias, and political beliefs. Unpublished raw data. (link to file). 

Kissell, B. L., Gibson, B. (2019). Religious decline on RWA, ideology, and Trump tweets. Unpublished raw data. (link to file). 

Kissell, B. L., Gibson, B. (2019). The Induction of religious decline through Video Clips on authoritarianism, conservative ideology, and authoritarian behavior. Unpublished raw data. (link to file). 

Kissell, B. L., Gibson, B. (2019). Religious Threat and Writing about Religious Experience on the CRT, NC, and FI. Unpublished raw data. (link to file). 

Kissell, B. L., Gibson, B. (2019). Religious Threat and Writing about Religious Experience on the Bullshit Receptivity Scale (BRS). Unpublished raw data. (link to file). 

Kissell, B. L., Gibson, B. (2019). Religious Threat on Political and Religious Beliefs. Unpublished raw data. (link to file). 

Kissell, B. L., Gibson, B. (2019). Religious Threat on Evaluative Bias and Religious Beliefs. Unpublished raw data. (link to file). 

Kissell, B. L., Gibson, B. (2019). Religious Threat on Christianity/Muslim IAT. Unpublished raw data. (link to file). 

Kissell, B. L., Gibson, B. (2019). Religious Threat on Christianity/Muslim IAT and Religious and Political Beliefs. Unpublished raw data. (link to file). 

Kissell, B. L., Gibson, B. (2019). The Influence of Cellphones on Serial Associative Cognition: Pilot. Unpublished raw data. (link to file). 

Kissell, B. L., Gibson, B. (2019). The Influence of Cellphones on Serial Associative Cognition. Unpublished raw data. (link to file). 

Kissell, B. L., Gibson, B. (2019). The Influence of Mindfulness Meditation on Serial Associative Cognition. Unpublished raw data. (link to file). 

Kissell, B. L., Gibson, B. (2019). Teaching about the replication crisis: pilot. Unpublished raw data. (link to file). 

## Conference Presentations 

Kissell, B. L. (2017). The influence of physical position and prayer on cognitive style. The Cognition of Belief. Washington, D.C.: John Templeton Foundation.

Kissell, B. L. (2018). Has psychology always been so ideologically biased?: A historical argument for ideological diversity. SPSP Annual Convention. Atlanta, GA: Society for Personality and Social Psychology.

Kissell, B. L.; Gibson, B. (2019). Religious Decline, Political Ideology, and Authoritarianism. SCREE Annual Student Research and Creative Endeavors Exhibition. Mount Pleasant, MI: Central Michigan University.