---
title: "The Languages of Mathematics and Technology"
author: "Brian Kissell"
date: "2020-06-28T00:00:00Z"
output: html_document
featured: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

As an undergraduate psychology student, I worked with a quantitative psychologist who had a nice analogy that has stuck with me. He spoke about the process of learning a new language. After studying a language for a few years, one may travel to a new area where that language is spoken and be able to somewhat function in that new place. They may have the skills to ask for directions to a restroom, to order their food, and may have even developed a decent vocabulary. However, it is unlikely that this person will have the fluency and skills necessary to communicate with others in a manner that is productive or meaningful. To truly take advantage of a new language, and to gain the skills to express oneself in a proficient manner, it can take a large amount of work and time. However, it can also be tremendously rewarding. 

This researcher would argue that it can be helpful to think about math as a language. He argued that there were too many within psychology who were only functioning at a basic (purely functional) level, and these people could benefit greatly if they would work to gain a fluency with the language of mathematics. I will add to the analogy by saying that the same could be said about the technological tools that are used within psychology. While most utilize sophisticated technologies for data collection and analysis, I would argue that many researchers within psychology are far from fluent in the language of technology and programming. Many seem content with using technology at a purely functional level, but I believe that for those who really want to explore and understand the targets of their research will need to develop a fluency with the languages of mathematics and technology.

Within the past two years, I have found myself drawn away from academic psychology, and instead have decided to enter the world of data-science. For those who are unfamiliar, data science is an interdisciplinary field that attempts to utilize scientific methodologies, statistical techniques, and algorithms – with a strong emphasis on programming, technology, and mathematics – to gain insights into the large array of data that is being made available by technology. I believe that the fields of both data science and psychology have a great deal to teach one another, and I am interested in exploring what those lessons are. As an attempt to begin that exploration, I am beginning a series on lessons that psychologological researchers can learn from data science. Some of the topics that I will explore in this series include lessons on data visualization, web scraping, data cleaning, exploratory data analysis, cross validation, textual analysis, natural linguistic processing, supervised and unsupervised machine learning, time series analysis, survival analysis, file management, database management, deep learning, many programming languages, and more. If there are topics that you would like me to discuss, or tutorials that you would like me to design, please let me know in the comment section. I look forward to exploring these topics with you.