---
title: "Science Communication"
author: "Brian Kissell"
date: "2020-07-08T04:00:00Z"
output: html_document
featured: True
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Why do scientists study what they choose to study? Why would one dedicate their life towards gaining the complex technical skills that allow for scientific pursuit? I believe that most of us entered scientific disciplines because we believe that science can bring about incredible insight & understanding that can be used to improve the lives of people. For the past eight to ten years, I have dedicated a significant portion of time attempting to develop the skills necessary to help real people understand complex scientific research. I have done this because I believe that scientific research should be utilized and for that to take place, real people need to be persuaded of its value.

During my undergraduate education, I created the methodology for psychology podcast in which I created more than 60 episodes. In these episodes, I interviewed experts in the field about their research and the methods they used. The purpose was to present academic research in a manner that could be understood by a general audience. I took down the podcast to allow me to focus on graduate school, but you can find the archived podcast information [here](https://methodologyforpsychology.wordpress.com/). My time within my graduate program also provided me with numerous opportunities to develop skills related to science communication. I was a teaching assistant for four semesters, and I was the course instructor for six semesters in which I taught multiple topics (i.e., research methods, social psychology, and stress). I was also able to write numerous research manuscripts, and to present my results in many poster sessions and talks.

There are numerous technologies and techniques that help to facilitate good science communication. Some of my favorite data visualization tools are *ggplot2*, *matplotlib*, *tableau*, and *power bi*. For manuscripts, as well as most written types of reports, I tend to use *R Markdown*. I use *R Studio* and *blogdown* to run my website (which I host on *github*). I also tend to construct dashboards with *rshiny* and *shinydashboards*.
